const modifiers = {
    //diacritics
  voiceless: { symbol: "̥", appliesTo: "consonant" },
  voiced: { symbol: "̬", appliesTo: "consonant" },
  aspirated: { symbol: "ʰ", appliesTo: "consonant" },
  more_rounded: { symbol: "̹", appliesTo: "vowel" },
  less_rounded: { symbol: "̜", appliesTo: "vowel" },
  advanced: { symbol: "̟", appliesTo: "consonant" },
  retracted: { symbol: "̠", appliesTo: "consonant" },
  centralized: { symbol: "̈", appliesTo: "vowel" },
  mid_centralized: { symbol: "̽", appliesTo: "vowel" },
  syllabic: { symbol: "̩", appliesTo: "consonant" },
  non_syllabic: { symbol: "̯", appliesTo: "vowel" },
  dental: { symbol: "̪", appliesTo: "consonant" },
  apical: { symbol: "̺", appliesTo: "consonant" },
  laminal: { symbol: "̻", appliesTo: "consonant" },
  velarized_or_pharyngealized: { symbol: "ˠ", appliesTo: "consonant" },
  palatalized: { symbol: "ʲ", appliesTo: "consonant" },
  labialized: { symbol: "ʷ", appliesTo: "consonant" },
  pharyngealized: { symbol: "ˤ", appliesTo: "consonant" },
  nasalized: { symbol: "̃", appliesTo: ["vowel", "consonant"] },
  rhoticity: { symbol: "˞", appliesTo: "vowel" },
  length_half_long: { symbol: "ˑ", appliesTo: ["vowel","consonant"] },
  length_long: { symbol: "ː", appliesTo: ["vowel","consonant"] },
  extra_short: { symbol: "̆", appliesTo: ["vowel","consonant"] },
  voiceless_flap: { symbol: "̥̆", appliesTo: "consonant" },
  creaky_voice: { symbol: "̰", appliesTo: ["vowel","consonant"] },
  breathy_voice: { symbol: "̤", appliesTo: ["vowel","consonant"] },
  linguolabial: { symbol: "̼", appliesTo: "consonant" },
  raised: { symbol: "̝", appliesTo: ["vowel","consonant"] },
  lowered: { symbol: "̞", appliesTo: ["vowel","consonant"] },
  advanced_tongue_root: { symbol: "̘", appliesTo: "vowel" },
  retracted_tongue_root: { symbol: "̙", appliesTo: "vowel" },
  velarized: { symbol: "̴", appliesTo: "consonant" },
  //tones and accents
  high_tone: { symbol: "́", appliesTo: ["vowel","consonant"] },
  low_tone: { symbol: "̀", appliesTo: ["vowel","consonant"] },
  rising_tone: { symbol: "̌", appliesTo: ["vowel","consonant"] },
  falling_tone: { symbol: "̂", appliesTo: ["vowel","consonant"] },
  extra_high_tone: { symbol: "᷄", appliesTo: ["vowel","consonant"] },
  extra_low_tone: { symbol: "᷅", appliesTo: ["vowel","consonant"] },
  downstep: { symbol: "ꜜ", appliesTo: ["vowel","consonant"] },
  upstep: { symbol: "ꜛ", appliesTo: ["vowel","consonant"] },
  no_audible_release: { symbol: "̚", appliesTo: "consonant" },
  extra_high_pitch: { symbol: "᷄", appliesTo: ["vowel","consonant"] },
  extra_low_pitch: { symbol: "᷅", appliesTo: ["vowel","consonant"] }
};